In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(pd.__version__)

2.2.3

In [3]:
import pandas as pd

race_results = pd.read_csv("../Data/raw/kaggle/f1_2024_race_results.csv")

race_results.head()

,race_id,race_name,circuit,city,country,circuit_length_km,total_laps,position,driver_name,team,nationality,car_number,race_time,points,fastest_lap,pole_position
0,1,Bahrain Grand Prix,Bahrain International Circuit,Sakhir,Bahrain,5.412,57,1,Max Verstappen,Red Bull Racing,NED,1,1:35:17.520,25,No,Yes
1,1,Bahrain Grand Prix,Bahrain International Circuit,Sakhir,Bahrain,5.412,57,2,Lewis Hamilton,Mercedes,GBR,44,+11.472,18,No,No
2,1,Bahrain Grand Prix,Bahrain International Circuit,Sakhir,Bahrain,5.412,57,3,Carlos Sainz,Ferrari,ESP,55,+18.138,15,No,No
3,1,Bahrain Grand Prix,Bahrain International Circuit,Sakhir,Bahrain,5.412,57,4,Sergio Perez,Red Bull Racing,MEX,11,+84.310,12,Yes,No
4,1,Bahrain Grand Prix,Bahrain International Circuit,Sakhir,Bahrain,5.412,57,5,George Russell,Mercedes,GBR,63,+45.823,10,No,No

In [4]:
race_results.info()
race_results.shape
race_results.columns
race_results.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   race_id            480 non-null    int64
 1   race_name          480 non-null    object
 2   circuit            480 non-null    object
 3   city               480 non-null    object
 4   country            480 non-null    object
 5   circuit_length_km  480 non-null    float64
 6   total_laps         480 non-null    int64
 7   position           480 non-null    int64
 8   driver_name        480 non-null    object
 9   team               480 non-null    object
 10  nationality        480 non-null    object
 11  car_number         480 non-null    int64
 12  race_time          480 non-null    object
 13  points             480 non-null    int64
 14  fastest_lap        480 non-null    object
 15  pole_position      480 non-null    object
dtypes: float64(1), int64(5), object(10)
memory usage: 60.1+ KB

,race_id,circuit_length_km,total_laps,position,car_number,points
count,480.000000,480.000000,480.000000,480.000000,480.000000,480.000000
mean,12.500000,5.189792,60.208333,10.500000,27.300000,5.050000
std,6.929408,0.813279,8.769749,5.772297,23.710361,7.180175
min,1.000000,3.337000,44.000000,1.000000,1.000000,0.000000
25%,6.750000,4.376000,53.000000,5.750000,10.750000,0.000000
50%,12.500000,5.346500,57.500000,10.500000,21.000000,0.500000
75%,18.250000,5.796500,70.000000,15.250000,34.250000,8.500000
max,24.000000,7.004000,78.000000,20.000000,81.000000,25.000000

In [5]:
race_results.isnull().sum()

race_id              0
race_name            0
circuit              0
city                 0
country              0
circuit_length_km    0
total_laps           0
position             0
driver_name          0
team                 0
nationality          0
car_number           0
race_time            0
points               0
fastest_lap          0
pole_position        0
dtype: int64

In [6]:
race_results.duplicated().sum()

np.int64(0)

In [7]:
race_results.dtypes

race_id                int64
race_name             object
circuit               object
city                  object
country               object
circuit_length_km    float64
total_laps             int64
position               int64
driver_name           object
team                  object
nationality           object
car_number             int64
race_time             object
points                 int64
fastest_lap           object
pole_position         object
dtype: object

In [8]:
race_results.to_csv("../Data/processed/race_results_clean.csv", index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!