In [1]:
!pip install fastf1

Collecting fastf1
  Downloading fastf1-3.8.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (44.0.1)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (3.10.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (2.1.3)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (2.2.3)
Requirement already satisfied: platformdirs in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (4.3.7)
Requirement already satisfied: pydantic in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (2.10.3)
Requirement already satisfied: pyjwt in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (2.10.1)
Requirement already satisfied: python-dateutil in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.14.5-cp313-cp313-win_amd64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.30.0 in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in c:\users\iamm4\anaconda3\lib\site-packages (from fastf1) (1.15.3)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Collecting websockets>=10.3 (from fastf1)
  Downloading websockets-16.1.1-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\iamm4\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\iamm4\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\iamm4\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\iamm4\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\iamm4\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\iamm4\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\iamm4\anaconda3\lib\site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.2.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\iamm4\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\iamm4\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\iamm4\anaconda3\lib\site-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\iamm4\anaconda3\lib\site-packages (from requests>=2.30.0->fastf1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\iamm4\anaconda3\lib\site-packages (from requests>=2.30.0->fastf1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\iamm4\anaconda3\lib\site-packages (from requests>=2.30.0->fastf1) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\iamm4\anaconda3\lib\site-packages (from requests>=2.30.0->fastf1) (2025.4.26)
Requirement already satisfied: attrs>=21.2 in c:\users\iamm4\anaconda3\lib\site-packages (from requests-cache>=1.0.0->fastf1) (24.3.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Collecting attrs>=21.2 (from requests-cache>=1.0.0->fastf1)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting typing-extensions>=4.14.0 (from cattrs>=22.2->requests-cache>=1.0.0->fastf1)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: cffi>=1.12 in c:\users\iamm4\anaconda3\lib\site-packages (from cryptography->fastf1) (1.17.1)
Requirement already satisfied: pycparser in c:\users\iamm4\anaconda3\lib\site-packages (from cffi>=1.12->cryptography->fastf1) (2.21)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\iamm4\anaconda3\lib\site-packages (from pydantic->fastf1) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\iamm4\anaconda3\lib\site-packages (from pydantic->fastf1) (2.27.1)
Collecting msgpack==1.1.2 (from signalrcore->fastf1)
  Downloading msgpack-1.1.2-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Downloading fastf1-3.8.3-py3-none-any.whl (135 kB)
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Downloading websockets-16.1.1-cp313-cp313-win_amd64.whl (180 kB)
Downloading rapidfuzz-3.14.5-cp313-cp313-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.5 MB 4.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.9 MB/s eta 0:00:00
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
Downloading msgpack-1.1.2-cp313-cp313-win_amd64.whl (72 kB)
Installing collected packages: websockets, url-normalize, typing-extensions, rapidfuzz, msgpack, attrs, signalrcore, cattrs, timple, requests-cache, fastf1

   ----------------------------------------  0/11 [websockets]
   ----------------------------------------  0/11 [websockets]
   ----------------------------------------  0/11 [websockets]
   ----------------------------------------  0/11 [websockets]
   ----------------------------------------  0/11 [websockets]
   --- ------------------------------------  1/11 [url-normalize]
  Attempting uninstall: typing-extensions
   --- ------------------------------------  1/11 [url-normalize]
    Found existing installation: typing_extensions 4.12.2
   --- ------------------------------------  1/11 [url-normalize]
    Uninstalling typing_extensions-4.12.2:
   --- ------------------------------------  1/11 [url-normalize]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
      Successfully uninstalled typing_extensions-4.12.2
   ------- --------------------------------  2/11 [typing-extensions]
   ------- --------------------------------  2/11 [typing-extensions]
   ---------- -----------------------------  3/11 [rapidfuzz]
   ---------- -----------------------------  3/11 [rapidfuzz]
  Attempting uninstall: msgpack
   ---------- -----------------------------  3/11 [rapidfuzz]
   -------------- -------------------------  4/11 [msgpack]
    Found existing installation: msgpack 1.0.3
   -------------- -------------------------  4/11 [msgpack]
    Uninstalling msgpack-1.0.3:
   -------------- -------------------------  4/11 [msgpack]
      Successfully uninstalled msgpack-1.0.3
   -------------- -------------------------  4/11 [msgpack]
  Attempting uninstall: attrs
   -------------- -------------------------  4/11 [msgpack]
   ------------------ ---------------------  5/11 [attrs]
    Found existing installation: attrs 24.3.0
   ------------------ ---------------------  5/11 [attrs]
    Uninstalling attrs-24.3.0:
   ------------------ ---------------------  5/11 [attrs]
      Successfully uninstalled attrs-24.3.0
   ------------------ ---------------------  5/11 [attrs]
   ------------------ ---------------------  5/11 [attrs]
   --------------------- ------------------  6/11 [signalrcore]
   --------------------- ------------------  6/11 [signalrcore]
   --------------------- ------------------  6/11 [signalrcore]
   ------------------------- --------------  7/11 [cattrs]
   ------------------------- --------------  7/11 [cattrs]
   ------------------------- --------------  7/11 [cattrs]
   ------------------------- --------------  7/11 [cattrs]
   ----------------------------- ----------  8/11 [timple]
   -------------------------------- -------  9/11 [requests-cache]
   -------------------------------- -------  9/11 [requests-cache]
   ------------------------------------ --- 10/11 [fastf1]
   ------------------------------------ --- 10/11 [fastf1]
   ---------------------------------------- 11/11 [fastf1]

Successfully installed attrs-26.1.0 cattrs-26.1.0 fastf1-3.8.3 msgpack-1.1.2 rapidfuzz-3.14.5 requests-cache-1.3.3 signalrcore-1.0.2 timple-0.1.8 typing-extensions-4.16.0 url-normalize-3.0.0 websockets-16.1.1

In [1]:
import fastf1

print("FastF1 version:", fastf1.__version__)

FastF1 version: 3.8.3

In [5]:
import os

print(os.getcwd())

C:\Users\iamm4\OneDrive\Desktop\Formula1_Dissertation\notebooks

In [6]:
import os

print(os.path.exists("../Data"))
print(os.path.exists("../Data/raw"))
print(os.path.exists("../Data/raw/kaggle"))
print(os.path.exists("../Data/raw/fastf1"))

True
True
True
False

In [7]:
import os

os.makedirs("../Data/raw/fastf1", exist_ok=True)

print("Folder created!")

Folder created!

In [8]:
print(os.path.exists("../Data/raw/fastf1"))

True

In [9]:
import fastf1

fastf1.Cache.enable_cache("../Data/raw/fastf1")

print("Cache enabled successfully!")

Cache enabled successfully!

In [10]:
import fastf1

# Load the 2024 Bahrain Grand Prix Race session
session = fastf1.get_session(2024, "Bahrain", "R")

print("Loading session...")
session.load()

print("Session loaded successfully!")

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

Loading session...

req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

Session loaded successfully!

In [11]:
session.results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671c6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:31:44.742000,Finished,26.0,57.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671c6,red_bull,Sergio,Perez,Sergio Perez,...,2.0,2,5.0,NaT,NaT,NaT,0 days 00:00:22.457000,Finished,18.0,57.0
55,55,C SAINZ,SAI,sainz,Ferrari,e8002d,ferrari,Carlos,Sainz,Carlos Sainz,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:25.110000,Finished,15.0,57.0
16,16,C LECLERC,LEC,leclerc,Ferrari,e8002d,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,4,2.0,NaT,NaT,NaT,0 days 00:00:39.669000,Finished,12.0,57.0
63,63,G RUSSELL,RUS,russell,Mercedes,27f4d2,mercedes,George,Russell,George Russell,...,5.0,5,3.0,NaT,NaT,NaT,0 days 00:00:46.788000,Finished,10.0,57.0

In [13]:
session.results.info()

<class 'fastf1.core.SessionResults'>
Index: 20 entries, 1 to 2
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        20 non-null     object
 1   BroadcastName       20 non-null     object
 2   Abbreviation        20 non-null     object
 3   DriverId            20 non-null     object
 4   TeamName            20 non-null     object
 5   TeamColor           20 non-null     object
 6   TeamId              20 non-null     object
 7   FirstName           20 non-null     object
 8   LastName            20 non-null     object
 9   FullName            20 non-null     object
 10  HeadshotUrl         20 non-null     object
 11  CountryCode         20 non-null     object
 12  Position            20 non-null     float64
 13  ClassifiedPosition  20 non-null     object
 14  GridPosition        20 non-null     float64
 15  Q1                  0 non-null      timedelta64[ns]
 16  Q2                  0 non-null      timedelta64[ns]
 17  Q3                  0 non-null      timedelta64[ns]
 18  Time                20 non-null     timedelta64[ns]
 19  Status              20 non-null     object
 20  Points              20 non-null     float64
 21  Laps                20 non-null     float64
dtypes: float64(4), object(14), timedelta64[ns](4)
memory usage: 3.6+ KB

In [14]:
session.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.266000,...,False,Red Bull Racing,0 days 00:59:59.911000,2024-03-02 15:03:42.342,12,1.0,False,,False,False
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2.0,1.0,NaT,NaT,0 days 00:00:30.916000,0 days 00:00:41.661000,...,False,Red Bull Racing,0 days 01:01:37.489000,2024-03-02 15:05:19.920,1,1.0,False,,False,True
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3.0,1.0,NaT,NaT,0 days 00:00:30.999000,0 days 00:00:41.966000,...,False,Red Bull Racing,0 days 01:03:13.785000,2024-03-02 15:06:56.216,1,1.0,False,,False,True
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4.0,1.0,NaT,NaT,0 days 00:00:30.931000,0 days 00:00:41.892000,...,False,Red Bull Racing,0 days 01:04:50.538000,2024-03-02 15:08:32.969,1,1.0,False,,False,True
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5.0,1.0,NaT,NaT,0 days 00:00:31.255000,0 days 00:00:42.056000,...,False,Red Bull Racing,0 days 01:06:27.185000,2024-03-02 15:10:09.616,1,1.0,False,,False,True

In [15]:
session.laps.info()

<class 'fastf1.core.Laps'>
RangeIndex: 1129 entries, 0 to 1128
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                1129 non-null   timedelta64[ns]
 1   Driver              1129 non-null   object
 2   DriverNumber        1129 non-null   object
 3   LapTime             1127 non-null   timedelta64[ns]
 4   LapNumber           1129 non-null   float64
 5   Stint               1129 non-null   float64
 6   PitOutTime          43 non-null     timedelta64[ns]
 7   PitInTime           43 non-null     timedelta64[ns]
 8   Sector1Time         1108 non-null   timedelta64[ns]
 9   Sector2Time         1129 non-null   timedelta64[ns]
 10  Sector3Time         1129 non-null   timedelta64[ns]
 11  Sector1SessionTime  1107 non-null   timedelta64[ns]
 12  Sector2SessionTime  1129 non-null   timedelta64[ns]
 13  Sector3SessionTime  1129 non-null   timedelta64[ns]
 14  SpeedI1             1129 non-null   float64
 15  SpeedI2             1129 non-null   float64
 16  SpeedFL             1086 non-null   float64
 17  SpeedST             1129 non-null   float64
 18  IsPersonalBest      1129 non-null   bool
 19  Compound            1129 non-null   object
 20  TyreLife            1129 non-null   float64
 21  FreshTyre           1129 non-null   bool
 22  Team                1129 non-null   object
 23  LapStartTime        1129 non-null   timedelta64[ns]
 24  LapStartDate        1129 non-null   datetime64[ns]
 25  TrackStatus         1129 non-null   object
 26  Position            1129 non-null   float64
 27  Deleted             1129 non-null   bool
 28  DeletedReason       1129 non-null   object
 29  FastF1Generated     1129 non-null   bool
 30  IsAccurate          1129 non-null   bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 235.0+ KB

In [16]:
session.laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [17]:
session.results.to_csv("../Data/raw/fastf1/bahrain_2024_results.csv", index=False)

session.laps.to_csv("../Data/raw/fastf1/bahrain_2024_laps.csv", index=False)

print("Files saved successfully!")

Files saved successfully!

In [18]:
session.laps.to_csv(
    "../Data/raw/fastf1/bahrain_2024_laps.csv",
    index=False
)

print("Lap data saved!")

Lap data saved!

In [19]:
weather = session.weather_data

weather.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:14.093000,18.9,46.0,1017.1,False,26.5,162,0.9
1,0 days 00:01:14.084000,18.9,46.0,1017.0,False,26.5,55,1.0
2,0 days 00:02:14.093000,18.9,46.0,1017.0,False,26.5,55,1.0
3,0 days 00:03:14.090000,18.9,45.0,1017.0,False,26.2,85,1.1
4,0 days 00:04:14.091000,18.9,46.0,1017.0,False,26.2,178,1.0

In [20]:
weather.to_csv(
    "../Data/raw/fastf1/bahrain_2024_weather.csv",
    index=False
)

print("Weather data saved!")

Weather data saved!

In [21]:
session.event

RoundNumber                                                   1
Country                                                 Bahrain
Location                                                 Sakhir
OfficialEventName    FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024
EventDate                                   2024-03-02 00:00:00
EventName                                    Bahrain Grand Prix
EventFormat                                        conventional
Session1                                             Practice 1
Session1Date                          2024-02-29 14:30:00+03:00
Session1DateUtc                             2024-02-29 11:30:00
Session2                                             Practice 2
Session2Date                          2024-02-29 18:00:00+03:00
Session2DateUtc                             2024-02-29 15:00:00
Session3                                             Practice 3
Session3Date                          2024-03-01 15:30:00+03:00
Session3DateUtc                             2024-03-01 12:30:00
Session4                                             Qualifying
Session4Date                          2024-03-01 19:00:00+03:00
Session4DateUtc                             2024-03-01 16:00:00
Session5                                                   Race
Session5Date                          2024-03-02 18:00:00+03:00
Session5DateUtc                             2024-03-02 15:00:00
F1ApiSupport                                               True
Name: 1, dtype: object